name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Espresso Tests
      uses: ReactiveCircus/android-emulator-runner@v2.26.0
      with:
        api-level: 28
        target: default
        arch: x86_64
        profile: Nexus 6
        script: adb shell am instrument -w -m -e clearPackageData true --no-window-animation -e package com.clearchannel.espressoTests.tests.sanity -e debug false com.clearchannel.iheartradio/androidx.test.runner.AndroidJUnitRunner
