name: Android Espresso Test CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    #runs-on: self-hosted
    #runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Compile
        run: |
          ./gradlew app:assembleDebug
          ./gradlew app:assembleDebugAndroidTest
        shell: bash

      - name: Build with Gradle
        run: ./gradlew app:assembleDebug

      #- name: Grant execute permission for gradlew
      #  run: chmod +x gradlew

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          # api-level: 29
          api-level: 23

          target: default
          arch: x86_64
          profile: pixel
          # profile: Nexus 6
          # profile: google-pixel_4a-0B021JEC200724
          # profile: emulator-5554
          script: ./gradlew app:connectedAndroidTest
        continue-on-error: true

      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: my-demo-app-android
          path: ./my-demo-app-android

  report:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }}
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: test-project

      - name: Report test result
        uses: linuxias/Android-test-result-printer@v0.1.0


    #   - name: Upload Test Reports Folder
    #     uses: actions/upload-artifact@v2
    #     if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
    #     with:
    #       name: gajiniraj
    #       path: app/build/reports/androidTests/connected/ # path to where the xml test results are stored
