name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew app:assembleDebug

      - name: Run instrumented test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: 'x86_64'
          api-level: 29
          target: default
          profile: pixel
          script: ./gradlew app:connectedDebugAndroidTest

      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: build
          path: ./build

  report:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }}
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Report test result
        uses: linuxias/Android-test-result-printer@v0.1.0