name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Run unit test
        run: ./gradlew testDebugUnitTest
        #run: ./gradlew app:connectedAndroidTest

      - name: Android Test Report
        uses: linuxias/Android-test-result-printer@v0.1.0